Generate pid file for BESClient

diff --git a/jobs/iem_agent/templates/iem_agent_ctl.erb b/jobs/iem_agent/templates/iem_agent_ctl.erb
--- a/jobs/iem_agent/templates/iem_agent_ctl.erb
+++ b/jobs/iem_agent/templates/iem_agent_ctl.erb
@@ -30,7 +30,14 @@ case $1 in
 
        touch $DONE_FILE
     fi
-    echo $$ > $PIDFILE
+
+    pid=`ps aux | grep -i BESClient | grep -v grep | awk {'print $2'}`
+    if [[ ! $pid =~ ^-?[0-9]+$ ]]; then
+        echo "Cannot detect a valid process ID for BESClient"
+        exit 1
+    fi
+
+    echo $pid > $PIDFILE
     ;;
 
   stop)
@@ -38,7 +45,7 @@ case $1 in
     ;;
 
   *)
-    echo "Usage: ctl {start|stop}" ;;
+    echo "Usage: iem_agent_ctl {start|stop}" ;;
 
 esac
 exit 0
